language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t eradityajoshi/docker-react -f Dockerfile.dev .

script:
  # - docker run eradityajoshi/docker-react npm run test -- --coverage
  - docker run -e CI=true eradityajoshi/docker-react npm run test
